name: Build and Push Docker Image

on:
  release:
    types: [created]

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Path to the Dockerfile and build context (current directory)
          platform: linux/amd64, linux/arm64, linux/arm/v7
          push: true # Push the image to the container registry
          tags: |
            $(echo ghcr.io/${{ github.repository_owner }}/webui-privaxy | tr '[:upper:]' '[:lower:]'):latest
            $(echo ghcr.io/${{ github.repository_owner }}/webui-privaxy | tr '[:upper:]' '[:lower:]'):${{ github.event.release.tag_name }}
